# Generated by Django 4.2.4 on 2023-08-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('count', models.IntegerField(default=1)),
                ('add_day', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('us_adrs', models.CharField(max_length=100)),
                ('reg_day', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_day', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='hw_app.product')),
                ('us_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_app.user')),
            ],
        ),
    ]
