# Generated by Django 4.2.4 on 2023-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0002_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_day',
            field=models.DateField(auto_now=True),
        ),
    ]
