# Generated by Django 4.2.4 on 2023-08-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0003_alter_order_order_day_alter_product_add_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_day',
            field=models.DateField(),
        ),
    ]
